/**
 * Real-mode data — today's clubs + players (EA FC 26 / 25-26 squads),
 * generated by tools/ingest_eafc.py into src/data/real/*.json.
 *
 * This is a SEPARATE universe from the legends pool (src/data/<league>/).
 * Real mode draws from EVERY club in the ingested leagues (no elite filter)
 * — 20 La Liga, 18 Bundesliga, the 2nd divisions, etc. — so you can manage
 * any real club. Players arrive with native multi-positions from the source,
 * so the side-slot problem doesn't exist here.
 *
 * Loaded outside the legends DATA/validateLeague pipeline (different schema
 * shape: clubs carry league/country, players carry age/potential).
 */
import type { Club, Player } from "./game-types";
import clubsJson from "@/data/real/clubs.json";
import playersJson from "@/data/real/players.json";
import transfersJson from "@/data/real/transfers.json";
import wonderkids26Json from "@/data/real/wonderkids26.json";

export interface RealClub extends Club {
  /** Real-league slug (es1, de1, it2, …). */
  league: string;
  leagueName: string;
  country: string;
}

export const REAL_CLUBS = clubsJson as RealClub[];

interface TransferMove {
  name: string;
  from: string;
  to: string;
}
export const REAL_TRANSFERS = (transfersJson as { transfers: TransferMove[] }).transfers;
export const REAL_TRANSFERS_AS_OF = (transfersJson as { _asOf: string })._asOf;

/** Layer the curated summer-2026 window on the snapshot: move a matched
 *  player (by name + current club) to his new club. A destination outside
 *  our leagues means he left the pool entirely. */
function applyTransfers(players: Player[]): Player[] {
  const clubIds = new Set(REAL_CLUBS.map((c) => c.id));
  const moves = new Map(REAL_TRANSFERS.map((t) => [`${t.from}|${t.name}`, t.to]));
  const out: Player[] = [];
  for (const p of players) {
    const to = moves.get(`${p.club}|${p.name}`);
    if (to === undefined) {
      out.push(p);
    } else if (clubIds.has(to)) {
      out.push({ ...p, club: to });
    }
    // else: moved out of our leagues → dropped.
  }
  return out;
}

interface Wonderkid26 {
  club: string;
  name: string;
  potential: number;
  fmRating: number;
}

/** The FM26 wonderkid overlay (curated from FMScout's top prospects, matched
 *  by name + club + age). For each matched player we RAISE his potential to
 *  the FMScout floor — never lower it — so these acclaimed teens actually
 *  develop into stars in a Real career (the season ageing reads `potential`
 *  as the ceiling). Keyed by the snapshot club, so apply BEFORE transfers. */
function applyWonderkids26(players: Player[]): Player[] {
  const floor = new Map(
    (wonderkids26Json as Wonderkid26[]).map((w) => [`${w.club}|${w.name}`, w.potential]),
  );
  if (floor.size === 0) return players;
  return players.map((p) => {
    const target = floor.get(`${p.club}|${p.name}`);
    if (target == null) return p;
    const potential = Math.max(p.potential ?? p.prime_rating, target);
    return potential === p.potential ? p : { ...p, potential };
  });
}

export const REAL_PLAYERS = applyTransfers(applyWonderkids26(playersJson as Player[]));

export interface RealLeague {
  slug: string;
  name: string;
  country: string;
  clubs: RealClub[];
}

let _leaguesCache: RealLeague[] | null = null;

/** Real leagues with their clubs, ordered top-flights first then by name. */
export function realLeagues(): RealLeague[] {
  if (_leaguesCache) return _leaguesCache;
  const by = new Map<string, RealLeague>();
  for (const c of REAL_CLUBS) {
    let lg = by.get(c.league);
    if (!lg) {
      lg = { slug: c.league, name: c.leagueName, country: c.country, clubs: [] };
      by.set(c.league, lg);
    }
    lg.clubs.push(c);
  }
  // Strongest club first within a league (nice default order for the picker).
  for (const lg of by.values()) lg.clubs.sort((a, b) => b.strength - a.strength);
  // Top flights (slug ending "1") before second tiers, then alphabetical.
  _leaguesCache = Array.from(by.values()).sort((a, b) => {
    const tier = (s: string) => (s.endsWith("1") ? 0 : 1);
    return tier(a.slug) - tier(b.slug) || a.name.localeCompare(b.name);
  });
  return _leaguesCache;
}

export function realLeagueName(slug: string | null | undefined): string | undefined {
  return REAL_CLUBS.find((c) => c.league === slug)?.leagueName;
}

/** Real-mode career pool: every ingested club (no elite filter — Real mode
 *  is about managing real clubs, not just super-teams). */
export function realCareerClubs(): Club[] {
  return REAL_CLUBS;
}

/** Every real player (all belong to an ingested club). */
export function realCareerPlayers(): Player[] {
  return REAL_PLAYERS;
}

/** A club's full real roster (post-transfer-overlay). */
export function realClubRoster(clubId: string): Player[] {
  return REAL_PLAYERS.filter((p) => p.club === clubId);
}

/** Rival-manager snapshot shape (structurally matches the career store's
 *  RivalManagerSave — kept local to avoid a store→data import cycle). */
export interface RealRival {
  id: string;
  name: string;
  badge: string;
  color: string;
  archetypeName: string;
  archetypeStyle: string;
  foundingClubId: string;
  squad: Player[];
}

/**
 * Build the AI rivals for a real league — every club except the user's, each
 * with its real roster. When the user is JOINING from another tier (promoted
 * or relegated), the weakest club is dropped to keep the division its real
 * size (the side that swapped places with you).
 */
export function buildRealRivals(slug: string, userClubId: string): RealRival[] {
  const lg = realLeagues().find((l) => l.slug === slug);
  if (!lg) return [];
  let clubs = lg.clubs.filter((c) => c.id !== userClubId);
  if (!lg.clubs.some((c) => c.id === userClubId)) {
    clubs = [...clubs].sort((a, b) => b.strength - a.strength).slice(0, lg.clubs.length - 1);
  }
  return clubs.map((c) => ({
    id: c.id,
    name: c.name,
    badge: c.short,
    color: c.color,
    archetypeName: c.name,
    archetypeStyle: "balanced",
    foundingClubId: c.id,
    squad: realClubRoster(c.id),
  }));
}

/** The real league a club plays in (with all its clubs). */
export function realLeagueOf(clubId: string): RealLeague | undefined {
  const club = REAL_CLUBS.find((c) => c.id === clubId);
  if (!club) return undefined;
  return realLeagues().find((l) => l.slug === club.league);
}
