/**
 * Real-mode data — today's clubs + players (EA FC 26 / 25-26 squads),
 * generated by tools/ingest_eafc.py into src/data/real/*.json.
 *
 * This is a SEPARATE universe from the legends pool (src/data/<league>/).
 * Real mode draws from EVERY club in the ingested leagues (no elite filter)
 * — 20 La Liga, 18 Bundesliga, the 2nd divisions, etc. — so you can manage
 * any real club. Players arrive with native multi-positions from the source,
 * so the side-slot problem doesn't exist here.
 *
 * Loaded outside the legends DATA/validateLeague pipeline (different schema
 * shape: clubs carry league/country, players carry age/potential).
 */
import type { Club, Player } from "./game-types";
import clubsJson from "@/data/real/clubs.json";
import playersJson from "@/data/real/players.json";

export interface RealClub extends Club {
  /** Real-league slug (es1, de1, it2, …). */
  league: string;
  leagueName: string;
  country: string;
}

export const REAL_CLUBS = clubsJson as RealClub[];
export const REAL_PLAYERS = playersJson as Player[];

export interface RealLeague {
  slug: string;
  name: string;
  country: string;
  clubs: RealClub[];
}

let _leaguesCache: RealLeague[] | null = null;

/** Real leagues with their clubs, ordered top-flights first then by name. */
export function realLeagues(): RealLeague[] {
  if (_leaguesCache) return _leaguesCache;
  const by = new Map<string, RealLeague>();
  for (const c of REAL_CLUBS) {
    let lg = by.get(c.league);
    if (!lg) {
      lg = { slug: c.league, name: c.leagueName, country: c.country, clubs: [] };
      by.set(c.league, lg);
    }
    lg.clubs.push(c);
  }
  // Strongest club first within a league (nice default order for the picker).
  for (const lg of by.values()) lg.clubs.sort((a, b) => b.strength - a.strength);
  // Top flights (slug ending "1") before second tiers, then alphabetical.
  _leaguesCache = Array.from(by.values()).sort((a, b) => {
    const tier = (s: string) => (s.endsWith("1") ? 0 : 1);
    return tier(a.slug) - tier(b.slug) || a.name.localeCompare(b.name);
  });
  return _leaguesCache;
}

export function realLeagueName(slug: string | null | undefined): string | undefined {
  return REAL_CLUBS.find((c) => c.league === slug)?.leagueName;
}

/** Real-mode career pool: every ingested club (no elite filter — Real mode
 *  is about managing real clubs, not just super-teams). */
export function realCareerClubs(): Club[] {
  return REAL_CLUBS;
}

/** Every real player (all belong to an ingested club). */
export function realCareerPlayers(): Player[] {
  return REAL_PLAYERS;
}
