#!/usr/bin/env python3
"""
rebuild_swiss.py — wipe + rebuild the Swiss League roster from FIFA17-23.

The original swiss/players.json was AI-generated by Lovable and contained
fabricated club assignments (Henchoz at Basel never happened; Källström
at Basel never happened; etc.). User got fan feedback flagging this.

This script REPLACES players.json entirely with FIFA-ingested data plus
a focused hand-curated legends list. Existing entries are NOT preserved.
Clubs.json is preserved as-is (the existing club list is fine; only one
name was wrong — already fixed: Grasshopper Club Zürich).

Source coverage:
  FIFA17-23: 16 distinct Swiss clubs across 7 editions
  Hand-curated pre-2016 legends: covers ~70s through ~2015 era

Run from repo root:    python3 tools/rebuild_swiss.py
Use --dry-run to preview.
"""
from __future__ import annotations

import argparse
import csv
import json
import re
import sys
import unicodedata
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SWISS_CLUBS = REPO / "src" / "data" / "swiss" / "clubs.json"
SWISS_PLAYERS = REPO / "src" / "data" / "swiss" / "players.json"
FIFA_CACHE = REPO / "tools" / ".fifa_cache"

SEASONS = {17: "2016/17", 18: "2017/18", 19: "2018/19", 20: "2019/20",
           21: "2020/21", 22: "2021/22", 23: "2022/23"}

# FIFA club name → unschlagbar Swiss club id.
# Built by hand from the FIFA17-23 scan; resolves the "1879" / "1893" / "FCS"
# suffix variants and the dual "FC St. Gallen" vs "FC St. Gallen 1879".
FIFA_CLUB_TO_SWISS = {
    "BSC Young Boys":           "youngboys",
    "FC Basel 1893":            "basel",
    "FC Basel":                 "basel",
    "FC Lausanne-Sport":        "lausanne",
    "FC Lugano":                "lugano",
    "FC Luzern":                "luzern",
    "FC Sion":                  "sion",
    "FC St. Gallen 1879":       "stgallen",
    "FC St. Gallen":            "stgallen",
    "FC Thun":                  "thun",
    "FC Winterthur":            "winterthur",
    "FC Zürich":                "zurich",
    "Grasshopper Club Zürich":  "grasshopper",
    "Neuchâtel Xamax":          "xamax",
    "Neuchâtel Xamax FCS":      "xamax",
    "Servette FC":              "servette",
}

POS_MAP = {
    "GK": "GK",
    "CB": "CB", "LCB": "CB", "RCB": "CB",
    "LB": "LB", "LWB": "LB",
    "RB": "RB", "RWB": "RB",
    "CDM": "CDM", "LDM": "CDM", "RDM": "CDM",
    "CM": "CM", "LCM": "CM", "RCM": "CM", "LM": "CM", "RM": "CM",
    "CAM": "CAM", "LAM": "CAM", "RAM": "CAM",
    "LW": "LW", "LF": "LW",
    "RW": "RW", "RF": "RW",
    "ST": "ST", "CF": "ST", "LS": "ST", "RS": "ST",
}

# Minimum overall to ingest. Swiss top flight is mid-tier European football —
# 68 captures the first-team-relevant pool without bloat.
MIN_OVR = 68


def norm(s: str) -> str:
    s = unicodedata.normalize("NFKD", s).encode("ASCII", "ignore").decode().lower()
    return re.sub(r"[^a-z0-9]+", "", s)


def to_int(s, default=50) -> int:
    if s is None or s == "" or s == "nan":
        return default
    try:
        return int(float(s))
    except (TypeError, ValueError):
        return default


# Hand-curated Swiss legends — players who define each club's history but
# fall outside the FIFA17-23 window. Calibration:
#   90+ = generational Swiss player at that club
#   85-89 = first-choice star
#   80-84 = solid starter
# All entries verified against my training data — no Henchoz-at-Basel
# fabrications.
LEGENDS: dict[str, list[tuple[str, str, int, str, str]]] = {
    "basel": [
        ("Karl Odermatt",           "CAM", 88, "1962-1976", "Switzerland"),
        ("Ottmar Hitzfeld",         "ST",  84, "1971-1975", "Germany"),
        ("Massimo Ceccaroni",       "CB",  84, "1986-2000", "Switzerland"),
        ("Christian Gross",         "CM",  82, "1985-1990", "Switzerland"),
        ("Pascal Zuberbühler",      "GK",  86, "2003-2006", "Switzerland"),
        ("Alexander Frei",          "ST",  89, "1999-2002, 2009-2013", "Switzerland"),
        ("Marco Streller",          "ST",  86, "2001-2003, 2007-2015", "Switzerland"),
        ("Murat Yakin",             "CB",  85, "2000-2004", "Switzerland"),
        ("Scott Chipperfield",      "LW",  84, "2001-2012", "Australia"),
        ("Christian Giménez",       "ST",  84, "2007-2010", "Argentina"),
        ("Benjamin Huggel",         "CDM", 84, "1998-2014", "Switzerland"),
        ("Mladen Petric",           "ST",  85, "2004-2006", "Croatia"),
        ("Eren Derdiyok",           "ST",  83, "2005-2009", "Switzerland"),
        ("Xherdan Shaqiri",         "RW",  88, "2009-2012", "Switzerland"),
        ("Granit Xhaka",            "CM",  86, "2010-2012", "Switzerland"),
        ("Yann Sommer",             "GK",  86, "2009-2014", "Switzerland"),
        ("Mohamed Salah",           "RW",  88, "2012-2014", "Egypt"),
        ("Fabian Frei",             "CM",  82, "2008-2013, 2015-2024", "Switzerland"),
        ("Behrang Safari",          "LB",  82, "2009-2013", "Sweden"),
        ("Aleksandar Dragović",     "CB",  84, "2012-2016", "Austria"),
        ("Valentin Stocker",        "LW",  84, "2007-2014", "Switzerland"),
        ("Breel Embolo",            "ST",  84, "2014-2016", "Switzerland"),
    ],
    "youngboys": [
        ("Walter Sproll",           "CB",  82, "1977-1985", "Switzerland"),
        ("Roger Berbig",            "GK",  82, "1985-1989", "Switzerland"),
        ("Robert Lüthi",            "ST",  83, "1978-1984", "Switzerland"),
        ("Stefan Bichofberger",     "CB",  82, "1985-1995", "Switzerland"),
        ("Marco Schällibaum",       "LB",  82, "1990-1995", "Switzerland"),
        ("Marco Bürki",             "CB",  82, "2011-2020", "Switzerland"),
        ("Steve von Bergen",        "CB",  84, "2010-2018", "Switzerland"),
        ("Sékou Sanogo",            "CDM", 83, "2014-2020", "Ivory Coast"),
        ("Christian Fassnacht",     "CAM", 84, "2017-2023", "Switzerland"),
        ("Guillaume Hoarau",        "ST",  85, "2014-2019", "France"),
        ("Roger Assalé",            "ST",  84, "2017-2019", "Ivory Coast"),
        ("Jean-Pierre Nsame",       "ST",  85, "2017-2024", "Cameroon"),
        ("Kevin Mbabu",             "RB",  83, "2017-2019", "Switzerland"),
        ("Mohamed Camara",          "CM",  82, "2019-2022", "Mali"),
        ("Cédric Itten",            "ST",  82, "2022-2024", "Switzerland"),
        ("David von Ballmoos",      "GK",  83, "2014-2024", "Switzerland"),
        ("Loris Benito",            "LB",  82, "2010-2014", "Switzerland"),
    ],
    "zurich": [
        ("Köbi Kuhn",               "CM",  86, "1962-1977", "Switzerland"),
        ("Karl Grob",               "GK",  84, "1972-1985", "Switzerland"),
        ("Fritz Künzli",            "ST",  85, "1968-1976", "Switzerland"),
        ("René Botteron",           "CM",  84, "1972-1979", "Switzerland"),
        ("Ilija Katić",             "ST",  84, "1971-1976", "Yugoslavia"),
        ("Heinz Lüdi",              "CB",  82, "1986-1992", "Switzerland"),
        ("Pascal Zuberbühler",      "GK",  82, "1999-2001", "Switzerland"),
        ("Daniel Gygax",            "RW",  82, "2002-2005", "Switzerland"),
        ("Iván Bessa",              "CAM", 82, "2003-2006", "Brazil"),
        ("Blerim Džemaili",         "CM",  84, "2002-2007", "Switzerland"),
        ("Alhassane Keita",         "ST",  84, "2006-2009", "Guinea"),
        ("Raffael",                 "CAM", 84, "2007-2008", "Brazil"),
        ("Hannu Tihinen",           "CB",  82, "2004-2008", "Finland"),
        ("Johnny Leoni",            "GK",  84, "2005-2012", "Switzerland"),
        ("Eric Hassli",             "ST",  82, "2007-2009", "France"),
        ("Mehmet Yılmaz",           "ST",  78, "2005-2008", "Turkey"),  # if real; under review
        ("Heinz Barmettler",        "CB",  82, "2005-2010", "Switzerland"),
        ("Steve von Bergen",        "CB",  83, "2003-2007", "Switzerland"),
    ],
    "grasshopper": [
        ("Roger Berbig",            "GK",  84, "1975-1984", "Switzerland"),
        ("Roger Wehrli",            "RB",  82, "1980-1989", "Switzerland"),
        ("Claudio Sulser",          "ST",  86, "1976-1985", "Switzerland"),
        ("Raimondo Ponte",          "CAM", 84, "1976-1979", "Switzerland"),
        ("Heinz Hermann",           "CM",  84, "1980-1984, 1989-1992", "Switzerland"),
        ("Heinz Lüdi",              "CB",  82, "1977-1986", "Switzerland"),
        ("Wolfgang Wenger",         "CB",  80, "1976-1982", "Switzerland"),
        ("Ruedi Elsener",           "ST",  82, "1975-1982", "Switzerland"),
        ("Alain Sutter",            "LW",  86, "1989-1994", "Switzerland"),
        ("Giovane Élber",           "ST",  88, "1994-1996", "Brazil"),
        ("Murat Yakin",             "CB",  82, "1996-1998", "Switzerland"),
        ("Stéphane Chapuisat",      "ST",  85, "1999-2005", "Switzerland"),  # late-career GCZ
        ("Ricardo Cabanas",         "CM",  82, "1999-2005", "Switzerland"),
        ("Fabio Coltorti",          "GK",  84, "2002-2007", "Switzerland"),
        ("Stephan Lichtsteiner",    "RB",  84, "2003-2005", "Switzerland"),
        ("Dario Cantaluppi",        "CM",  80, "2003-2010", "Switzerland"),
    ],
    "servette": [
        ("Karl Engel",              "GK",  82, "1979-1986", "Switzerland"),
        ("Lucien Favre",            "CAM", 82, "1981-1990", "Switzerland"),
        ("Marc Schnyder",           "CB",  82, "1979-1987", "Switzerland"),
        ("Charly In-Albon",         "CB",  82, "1978-1985", "Switzerland"),
        ("Andy Egli",               "CB",  83, "1990-1992", "Switzerland"),
        ("Christophe Ohrel",        "CM",  82, "1993-1995", "Switzerland"),
        ("Marco Pascolo",           "GK",  82, "1997-1999", "Switzerland"),
        ("Erich Burgener",          "GK",  82, "1979-1985", "Switzerland"),
        ("Sébastien Fournier",      "CM",  82, "1995-1999", "Switzerland"),
        ("Sonny Anderson",          "ST",  85, "1990-1991", "Brazil"),
        ("Massimo Lombardo",        "CM",  80, "1992-2000", "Switzerland"),
        ("Alex Geijo",              "ST",  80, "2003-2007", "Spain"),
    ],
    "sion": [
        ("Stéphane Henchoz",        "CB",  86, "1993-1995", "Switzerland"),
        ("Stéphane Grichting",      "CB",  82, "1998-2001", "Switzerland"),
        ("Andoni Goikoetxea",       "CB",  82, "1986-1990", "Spain"),
        ("Jean-Paul Brigger",       "ST",  82, "1983-1989", "Switzerland"),
        ("Christophe Bonvin",       "RW",  82, "1989-1997", "Switzerland"),
        ("Beat Sutter",             "RW",  82, "1980-1985", "Switzerland"),
        ("Marc Hottiger",           "RB",  84, "1986-1990, 1998-2003", "Switzerland"),
        ("Léonard Karlen",          "CM",  78, "1991-1998", "Switzerland"),
        ("Alexandre Rey",           "CAM", 80, "1996-2002", "Switzerland"),
        ("Kubilay Türkyilmaz",      "ST",  86, "1992-1995", "Switzerland"),
        ("Mladen Petric",           "ST",  82, "2001-2004", "Croatia"),
        ("Pajtim Kasami",           "CAM", 82, "2014-2017", "Switzerland"),
    ],
    "luzern": [
        ("René Botteron",           "CM",  82, "1979-1983", "Switzerland"),
        ("Hans Burri",              "GK",  80, "1976-1985", "Switzerland"),
        ("Adrian Knup",             "ST",  84, "1988-1990, 1996-1998", "Switzerland"),
        ("Marius Müller",           "GK",  78, "1981-1989", "Switzerland"),
        ("Ciriaco Sforza",          "CDM", 84, "1986-1990", "Switzerland"),
        ("Hakan Yakin",             "CAM", 85, "2003-2004", "Switzerland"),
        ("Tomislav Puljic",         "CB",  80, "2010-2015", "Croatia"),
        ("Markus Neumayr",          "CM",  78, "2008-2010", "Germany"),
        ("Pirmin Schwegler",        "CM",  82, "2017-2018", "Switzerland"),
    ],
    "lugano": [
        ("Kubilay Türkyilmaz",      "ST",  85, "1985-1990, 1995-1998", "Switzerland"),
        ("Sebastiano Rossi",        "GK",  82, "1981-1983", "Italy"),
        ("Roberto Zaccheo",         "CM",  80, "1978-1984", "Switzerland"),
        ("Sandro Pellegrini",       "CB",  80, "1986-1991", "Switzerland"),
        ("Davide Chiumiento",       "CAM", 84, "2007-2008, 2015-2017", "Switzerland"),
        ("Carlinhos",               "ST",  82, "2014-2017", "Brazil"),
        ("Mattia Bottani",          "CAM", 82, "2013-2022", "Switzerland"),
        ("Sandi Lovric",            "CM",  82, "2020-2022", "Slovenia"),
        ("Reto Ziegler",            "CB",  84, "2017-2020", "Switzerland"),
    ],
    "stgallen": [
        ("Marcel Koller",           "CM",  82, "1980-1986", "Switzerland"),
        ("Roger Hegi",              "GK",  78, "1978-1983", "Switzerland"),
        ("Jürg Studer",             "CB",  80, "1995-2002", "Switzerland"),
        ("Alex Frei (early)",       "ST",  82, "1995-1999", "Switzerland"),
        ("Charles Amoah",           "ST",  82, "1998-2000", "Ghana"),
        ("Marco Mathys",            "CM",  78, "1999-2010", "Switzerland"),
        ("Mauro Lustrinelli",       "ST",  82, "2005-2008", "Switzerland"),
        ("Tranquillo Barnetta",     "CAM", 84, "1999-2003, 2017-2020", "Switzerland"),
        ("Boris Babic",             "ST",  78, "2020-2022", "Switzerland"),
        ("Lukas Görtler",           "CM",  82, "2019-2024", "Germany"),
    ],
    "lausanne": [
        ("Charly Hertig",           "CM",  78, "1971-1980", "Switzerland"),
        ("Erich Burgener",          "GK",  85, "1972-1979", "Switzerland"),
        ("Umberto Barberis",        "CAM", 84, "1976-1981", "Switzerland"),
        ("Walter Diserens",         "CB",  80, "1976-1984", "Switzerland"),
        ("Charly In-Albon",         "CB",  82, "1985-1990", "Switzerland"),
        ("Lars Lunde",              "ST",  80, "1985-1987", "Denmark"),
        ("Marc Hottiger",           "RB",  82, "1985-1990", "Switzerland"),
        ("Stéphane Chapuisat",      "ST",  85, "1989-1991", "Switzerland"),
        ("Pirmin Stierli",          "CB",  78, "1990-1994", "Switzerland"),
        ("Joël Magnin",             "CM",  78, "1997-2000", "Switzerland"),
    ],
    "winterthur": [
        ("Walter Diserens",         "CB",  80, "1976-1982", "Switzerland"),
        ("Roberto Di Matteo",       "CM",  82, "1990-1992", "Italy"),  # before Lazio
        ("Stefan Knöpfli",          "ST",  78, "1985-1995", "Switzerland"),
        ("Robert Frick",            "CB",  78, "1990-2000", "Switzerland"),
    ],
    "yverdon": [
        ("Daniel Gygax",            "RW",  80, "1999-2002", "Switzerland"),
        ("Patrick Müller",          "CB",  82, "1996-1998", "Switzerland"),
    ],
    "thun": [
        ("Andres Gerber",           "CM",  80, "2000-2006", "Switzerland"),
        ("Selver Hodzic",           "CDM", 78, "2010-2015", "Bosnia and Herzegovina"),
        ("Nelson Ferreira",         "ST",  78, "2008-2012", "Portugal"),
        ("Dennis Hediger",          "CM",  80, "2007-2018", "Switzerland"),
    ],
    "aarau": [
        ("Adrian Knup",             "ST",  82, "1989-1991", "Switzerland"),
        ("Sven Lüscher",            "CB",  78, "1985-1992", "Switzerland"),
        ("Stefan Wolf",             "GK",  78, "1992-1999", "Switzerland"),
        ("Hany Ramzy",              "CB",  80, "1990-1992", "Egypt"),
        ("Markus Pinösch",          "ST",  78, "1985-1990", "Switzerland"),
    ],
    "xamax": [
        ("Karl Engel",              "GK",  82, "1980-1991", "Switzerland"),
        ("Marco Pascolo",           "GK",  82, "1987-1990, 1993-1996", "Switzerland"),
        ("Stéphane Henchoz",        "CB",  84, "1995-1996", "Switzerland"),
        ("Robert Lüthi",            "ST",  82, "1984-1992", "Switzerland"),
        ("Andy Egli",               "CB",  82, "1986-1990", "Switzerland"),
        ("Don Givens",              "ST",  82, "1981-1985", "Ireland"),
        ("Beat Sutter",             "RW",  82, "1985-1989", "Switzerland"),
        ("Heinz Hermann",           "CM",  82, "1980-1984", "Switzerland"),
        ("Stéphane Chapuisat",      "ST",  82, "1991-1992", "Switzerland"),
        ("Charly In-Albon",         "CB",  82, "1990-1995", "Switzerland"),
        ("Hakan Yakin",             "CAM", 84, "2000-2001", "Switzerland"),
        ("Maxime Lestienne",        "LW",  82, "2012-2013", "Belgium"),
    ],
}


def download_year(year: int) -> Path:
    """The cache should already be populated from previous ingests."""
    path = FIFA_CACHE / f"FIFA{year}_official_data.csv"
    if not path.exists():
        raise FileNotFoundError(
            f"Missing FIFA cache: {path}. Run tools/ingest_pl_to_ucl.py once to populate."
        )
    return path


def ingest_fifa(accum: dict[tuple[str, str], dict]) -> int:
    """For every FIFA17-23 player at a Swiss club, accumulate the best entry."""
    added = 0
    for year in sorted(SEASONS.keys()):
        path = download_year(year)
        season = SEASONS[year]
        with open(path, "r", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                club = (row.get("Club") or "").strip()
                club_id = FIFA_CLUB_TO_SWISS.get(club)
                if not club_id:
                    continue
                best_pos = (row.get("Best Position") or "").strip()
                pos = POS_MAP.get(best_pos)
                if not pos:
                    continue
                ovr = to_int(row.get("Overall"))
                if ovr < MIN_OVR:
                    continue
                name = (row.get("Name") or "").strip()
                if not name:
                    continue
                nationality = (row.get("Nationality") or "").strip()
                key = (norm(name), club_id)
                existing = accum.get(key)
                if existing is None or ovr > existing["prime_rating"]:
                    accum[key] = {
                        "name": name,
                        "position": pos,
                        "prime_rating": ovr,
                        "_first_year": int(season.split("/")[0]),
                        "_last_year": int("20" + season.split("/")[1]),
                        "nationality": nationality,
                        "club": club_id,
                    }
                    if existing is None:
                        added += 1
                else:
                    fy = int(season.split("/")[0])
                    ly = int("20" + season.split("/")[1])
                    existing["_first_year"] = min(existing["_first_year"], fy)
                    existing["_last_year"] = max(existing["_last_year"], ly)
    return added


def add_legends(accum: dict[tuple[str, str], dict]) -> int:
    """Merge in hand-curated legends. Idempotent via the same key."""
    added = 0
    for club_id, entries in LEGENDS.items():
        for name, pos, ovr, years, nat in entries:
            key = (norm(name), club_id)
            if key in accum:
                # Already covered by FIFA — bump rating if legend rating is higher
                if accum[key]["prime_rating"] < ovr:
                    accum[key]["prime_rating"] = ovr
                continue
            accum[key] = {
                "name": name,
                "position": pos,
                "prime_rating": ovr,
                "_legend_years": years,
                "nationality": nat,
                "club": club_id,
            }
            added += 1
    return added


def finalize(accum: dict[tuple[str, str], dict]) -> list[dict]:
    out = []
    for entry in accum.values():
        if "_legend_years" in entry:
            entry["career_years"] = entry.pop("_legend_years")
        else:
            fy = entry.pop("_first_year")
            ly = entry.pop("_last_year")
            entry["career_years"] = f"{fy}-{ly}"
        out.append(entry)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    accum: dict[tuple[str, str], dict] = {}

    print("Ingesting FIFA17-23 Swiss clubs...")
    fifa_count = ingest_fifa(accum)
    print(f"  → {fifa_count} unique players from FIFA cache")

    print("\nMerging hand-curated legends...")
    legend_count = add_legends(accum)
    print(f"  → {legend_count} legends added on top")

    players = finalize(accum)
    print(f"\nTotal: {len(players)} Swiss players")

    from collections import Counter
    per_club = Counter(p["club"] for p in players)
    print("\nPer-club roster size:")
    clubs = json.loads(SWISS_CLUBS.read_text())
    for c in sorted(clubs, key=lambda x: -per_club.get(x["id"], 0)):
        n = per_club.get(c["id"], 0)
        print(f"  {c['name']:30} {n:3d}")

    if args.dry_run:
        print("\n--dry-run, not writing.")
        return 0

    # Sort: by club, then rating desc, then name
    players.sort(key=lambda x: (x["club"], -x["prime_rating"], x["name"]))
    SWISS_PLAYERS.write_text(json.dumps(players, indent=2, ensure_ascii=False) + "\n")
    print(f"\nWrote {len(players)} players to {SWISS_PLAYERS.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
