/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeasonRouteImport } from './routes/season'
import { Route as ResultRouteImport } from './routes/result'
import { Route as GameRouteImport } from './routes/game'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as CareerRouteImport } from './routes/career'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareerSeasonRouteImport } from './routes/career.season'
import { Route as CareerPostseasonRouteImport } from './routes/career.postseason'
import { Route as CareerHistoryRouteImport } from './routes/career.history'
import { Route as CareerFoundRouteImport } from './routes/career.found'
import { Route as CareerDraftRouteImport } from './routes/career.draft'
import { Route as CareerCupRouteImport } from './routes/career.cup'

const SeasonRoute = SeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerSeasonRoute = CareerSeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => CareerRoute,
} as any)
const CareerPostseasonRoute = CareerPostseasonRouteImport.update({
  id: '/postseason',
  path: '/postseason',
  getParentRoute: () => CareerRoute,
} as any)
const CareerHistoryRoute = CareerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CareerRoute,
} as any)
const CareerFoundRoute = CareerFoundRouteImport.update({
  id: '/found',
  path: '/found',
  getParentRoute: () => CareerRoute,
} as any)
const CareerDraftRoute = CareerDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => CareerRoute,
} as any)
const CareerCupRoute = CareerCupRouteImport.update({
  id: '/cup',
  path: '/cup',
  getParentRoute: () => CareerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career': typeof CareerRouteWithChildren
  '/draft': typeof DraftRoute
  '/game': typeof GameRoute
  '/result': typeof ResultRoute
  '/season': typeof SeasonRoute
  '/career/cup': typeof CareerCupRoute
  '/career/draft': typeof CareerDraftRoute
  '/career/found': typeof CareerFoundRoute
  '/career/history': typeof CareerHistoryRoute
  '/career/postseason': typeof CareerPostseasonRoute
  '/career/season': typeof CareerSeasonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career': typeof CareerRouteWithChildren
  '/draft': typeof DraftRoute
  '/game': typeof GameRoute
  '/result': typeof ResultRoute
  '/season': typeof SeasonRoute
  '/career/cup': typeof CareerCupRoute
  '/career/draft': typeof CareerDraftRoute
  '/career/found': typeof CareerFoundRoute
  '/career/history': typeof CareerHistoryRoute
  '/career/postseason': typeof CareerPostseasonRoute
  '/career/season': typeof CareerSeasonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career': typeof CareerRouteWithChildren
  '/draft': typeof DraftRoute
  '/game': typeof GameRoute
  '/result': typeof ResultRoute
  '/season': typeof SeasonRoute
  '/career/cup': typeof CareerCupRoute
  '/career/draft': typeof CareerDraftRoute
  '/career/found': typeof CareerFoundRoute
  '/career/history': typeof CareerHistoryRoute
  '/career/postseason': typeof CareerPostseasonRoute
  '/career/season': typeof CareerSeasonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career'
    | '/draft'
    | '/game'
    | '/result'
    | '/season'
    | '/career/cup'
    | '/career/draft'
    | '/career/found'
    | '/career/history'
    | '/career/postseason'
    | '/career/season'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career'
    | '/draft'
    | '/game'
    | '/result'
    | '/season'
    | '/career/cup'
    | '/career/draft'
    | '/career/found'
    | '/career/history'
    | '/career/postseason'
    | '/career/season'
  id:
    | '__root__'
    | '/'
    | '/career'
    | '/draft'
    | '/game'
    | '/result'
    | '/season'
    | '/career/cup'
    | '/career/draft'
    | '/career/found'
    | '/career/history'
    | '/career/postseason'
    | '/career/season'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerRoute: typeof CareerRouteWithChildren
  DraftRoute: typeof DraftRoute
  GameRoute: typeof GameRoute
  ResultRoute: typeof ResultRoute
  SeasonRoute: typeof SeasonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/season': {
      id: '/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof SeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/season': {
      id: '/career/season'
      path: '/season'
      fullPath: '/career/season'
      preLoaderRoute: typeof CareerSeasonRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/postseason': {
      id: '/career/postseason'
      path: '/postseason'
      fullPath: '/career/postseason'
      preLoaderRoute: typeof CareerPostseasonRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/history': {
      id: '/career/history'
      path: '/history'
      fullPath: '/career/history'
      preLoaderRoute: typeof CareerHistoryRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/found': {
      id: '/career/found'
      path: '/found'
      fullPath: '/career/found'
      preLoaderRoute: typeof CareerFoundRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/draft': {
      id: '/career/draft'
      path: '/draft'
      fullPath: '/career/draft'
      preLoaderRoute: typeof CareerDraftRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/cup': {
      id: '/career/cup'
      path: '/cup'
      fullPath: '/career/cup'
      preLoaderRoute: typeof CareerCupRouteImport
      parentRoute: typeof CareerRoute
    }
  }
}

interface CareerRouteChildren {
  CareerCupRoute: typeof CareerCupRoute
  CareerDraftRoute: typeof CareerDraftRoute
  CareerFoundRoute: typeof CareerFoundRoute
  CareerHistoryRoute: typeof CareerHistoryRoute
  CareerPostseasonRoute: typeof CareerPostseasonRoute
  CareerSeasonRoute: typeof CareerSeasonRoute
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerCupRoute: CareerCupRoute,
  CareerDraftRoute: CareerDraftRoute,
  CareerFoundRoute: CareerFoundRoute,
  CareerHistoryRoute: CareerHistoryRoute,
  CareerPostseasonRoute: CareerPostseasonRoute,
  CareerSeasonRoute: CareerSeasonRoute,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerRoute: CareerRouteWithChildren,
  DraftRoute: DraftRoute,
  GameRoute: GameRoute,
  ResultRoute: ResultRoute,
  SeasonRoute: SeasonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
