/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CareerRouteImport } from './routes/career'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareerSeasonRouteImport } from './routes/career.season'
import { Route as CareerRecapRouteImport } from './routes/career.recap'
import { Route as CareerPostseasonRouteImport } from './routes/career.postseason'
import { Route as CareerHistoryRouteImport } from './routes/career.history'
import { Route as CareerFoundRouteImport } from './routes/career.found'
import { Route as CareerEuropeRouteImport } from './routes/career.europe'
import { Route as CareerDraftRouteImport } from './routes/career.draft'
import { Route as CareerCupRouteImport } from './routes/career.cup'

const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerSeasonRoute = CareerSeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => CareerRoute,
} as any)
const CareerRecapRoute = CareerRecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => CareerRoute,
} as any)
const CareerPostseasonRoute = CareerPostseasonRouteImport.update({
  id: '/postseason',
  path: '/postseason',
  getParentRoute: () => CareerRoute,
} as any)
const CareerHistoryRoute = CareerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CareerRoute,
} as any)
const CareerFoundRoute = CareerFoundRouteImport.update({
  id: '/found',
  path: '/found',
  getParentRoute: () => CareerRoute,
} as any)
const CareerEuropeRoute = CareerEuropeRouteImport.update({
  id: '/europe',
  path: '/europe',
  getParentRoute: () => CareerRoute,
} as any)
const CareerDraftRoute = CareerDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => CareerRoute,
} as any)
const CareerCupRoute = CareerCupRouteImport.update({
  id: '/cup',
  path: '/cup',
  getParentRoute: () => CareerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career': typeof CareerRouteWithChildren
  '/career/cup': typeof CareerCupRoute
  '/career/draft': typeof CareerDraftRoute
  '/career/europe': typeof CareerEuropeRoute
  '/career/found': typeof CareerFoundRoute
  '/career/history': typeof CareerHistoryRoute
  '/career/postseason': typeof CareerPostseasonRoute
  '/career/recap': typeof CareerRecapRoute
  '/career/season': typeof CareerSeasonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career': typeof CareerRouteWithChildren
  '/career/cup': typeof CareerCupRoute
  '/career/draft': typeof CareerDraftRoute
  '/career/europe': typeof CareerEuropeRoute
  '/career/found': typeof CareerFoundRoute
  '/career/history': typeof CareerHistoryRoute
  '/career/postseason': typeof CareerPostseasonRoute
  '/career/recap': typeof CareerRecapRoute
  '/career/season': typeof CareerSeasonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career': typeof CareerRouteWithChildren
  '/career/cup': typeof CareerCupRoute
  '/career/draft': typeof CareerDraftRoute
  '/career/europe': typeof CareerEuropeRoute
  '/career/found': typeof CareerFoundRoute
  '/career/history': typeof CareerHistoryRoute
  '/career/postseason': typeof CareerPostseasonRoute
  '/career/recap': typeof CareerRecapRoute
  '/career/season': typeof CareerSeasonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career'
    | '/career/cup'
    | '/career/draft'
    | '/career/europe'
    | '/career/found'
    | '/career/history'
    | '/career/postseason'
    | '/career/recap'
    | '/career/season'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career'
    | '/career/cup'
    | '/career/draft'
    | '/career/europe'
    | '/career/found'
    | '/career/history'
    | '/career/postseason'
    | '/career/recap'
    | '/career/season'
  id:
    | '__root__'
    | '/'
    | '/career'
    | '/career/cup'
    | '/career/draft'
    | '/career/europe'
    | '/career/found'
    | '/career/history'
    | '/career/postseason'
    | '/career/recap'
    | '/career/season'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerRoute: typeof CareerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/season': {
      id: '/career/season'
      path: '/season'
      fullPath: '/career/season'
      preLoaderRoute: typeof CareerSeasonRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/recap': {
      id: '/career/recap'
      path: '/recap'
      fullPath: '/career/recap'
      preLoaderRoute: typeof CareerRecapRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/postseason': {
      id: '/career/postseason'
      path: '/postseason'
      fullPath: '/career/postseason'
      preLoaderRoute: typeof CareerPostseasonRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/history': {
      id: '/career/history'
      path: '/history'
      fullPath: '/career/history'
      preLoaderRoute: typeof CareerHistoryRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/found': {
      id: '/career/found'
      path: '/found'
      fullPath: '/career/found'
      preLoaderRoute: typeof CareerFoundRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/europe': {
      id: '/career/europe'
      path: '/europe'
      fullPath: '/career/europe'
      preLoaderRoute: typeof CareerEuropeRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/draft': {
      id: '/career/draft'
      path: '/draft'
      fullPath: '/career/draft'
      preLoaderRoute: typeof CareerDraftRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/cup': {
      id: '/career/cup'
      path: '/cup'
      fullPath: '/career/cup'
      preLoaderRoute: typeof CareerCupRouteImport
      parentRoute: typeof CareerRoute
    }
  }
}

interface CareerRouteChildren {
  CareerCupRoute: typeof CareerCupRoute
  CareerDraftRoute: typeof CareerDraftRoute
  CareerEuropeRoute: typeof CareerEuropeRoute
  CareerFoundRoute: typeof CareerFoundRoute
  CareerHistoryRoute: typeof CareerHistoryRoute
  CareerPostseasonRoute: typeof CareerPostseasonRoute
  CareerRecapRoute: typeof CareerRecapRoute
  CareerSeasonRoute: typeof CareerSeasonRoute
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerCupRoute: CareerCupRoute,
  CareerDraftRoute: CareerDraftRoute,
  CareerEuropeRoute: CareerEuropeRoute,
  CareerFoundRoute: CareerFoundRoute,
  CareerHistoryRoute: CareerHistoryRoute,
  CareerPostseasonRoute: CareerPostseasonRoute,
  CareerRecapRoute: CareerRecapRoute,
  CareerSeasonRoute: CareerSeasonRoute,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerRoute: CareerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
